# Generated by Django 4.1.3 on 2023-02-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nameGoods", models.CharField(max_length=100)),
                ("compositionOfGoods", models.TextField()),
                ("pathImage", models.TextField(null=True)),
                ("weightGoods", models.CharField(max_length=10)),
                ("priceGoods", models.IntegerField()),
                ("favoriteGoods", models.BooleanField(default=False)),
                ("category", models.CharField(max_length=30)),
            ],
        ),
    ]
