# Generated by Django 4.1.3 on 2023-02-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goods",
            options={"verbose_name": "Goods", "verbose_name_plural": "Goods"},
        ),
        migrations.AddField(
            model_name="goods",
            name="file",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
