# Generated by Django 4.1.3 on 2023-02-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_alter_goods_options_goods_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goods",
            name="file",
        ),
        migrations.AlterField(
            model_name="goods",
            name="pathImage",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
