# Generated by Django 4.1.3 on 2023-02-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_remove_goods_file_alter_goods_pathimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="pathImage",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
