# Generated by Django 4.1.3 on 2023-03-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="favoriteGoods",
            field=models.BooleanField(default=False),
        ),
    ]
