# Generated by Django 4.1.3 on 2023-02-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_alter_goods_pathimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="pathImage",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
