# Generated by Django 4.1.3 on 2023-02-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_alter_goods_pathimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="pathImage",
            field=models.TextField(null=True),
        ),
    ]
